name = "hex-gram-schmidt"
defaultTargets = ["HexGramSchmidt"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries.git"
rev = "v4.30.0-rc2"

[[require]]
name = "HexMatrix"
git = "https://github.com/kim-em/hex-matrix.git"
rev = "2b6b1127c43e5e3a1fc935222376713f7bc843fc"

[[lean_lib]]
name = "HexGramSchmidt"
