name = "hex-gram-schmidt"
defaultTargets = ["HexGramSchmidt"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "da8a864cd17ccca780d8c76af403e88585bc4734"

[[require]]
name = "HexMatrix"
git = "https://github.com/leanprover/hex-matrix.git"
rev = "25cfbbd8a689eb782fad408c46a9c1796dd943b2"

[[require]]
name = "HexRowReduce"
git = "https://github.com/leanprover/hex-row-reduce.git"
rev = "967216591082d290bc3f9e1b7405effd910bdef9"

[[require]]
name = "HexDeterminant"
git = "https://github.com/leanprover/hex-determinant.git"
rev = "01c471058f6d7b84c4bc37a2d200f264f356328b"

[[require]]
name = "HexBareiss"
git = "https://github.com/leanprover/hex-bareiss.git"
rev = "4e0b52c59c96f20956db753ed2ed1ed9d11c59c4"

[[lean_lib]]
name = "HexGramSchmidt"
